# Generated by Django 2.2.2 on 2020-11-12 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0004_bids_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='provider',
        ),
    ]
